# This file has code to build and push a Docker image to Azure Container Registry (ACR) and GCR when a pull request is made.

name: Image Push to ACR
on: [pull_request]
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to ACR
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_REPO }}
            username: github-token
            password: ${{ secrets.ACR_PASSWORD }}
    
        # - name: Log in to Github Container Registry
        #   run: |
        #     echo ${{ secrets.GIT_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        # - name: Build and push Docker image
        #   run: |
        #     docker build -t ghcr.io/${{ github.repository_owner }}/my-app:latest .
        #     docker push ghcr.io/${{ github.repository_owner }}/my-app:latest

        # - name: Log in to Azure Container Registry
        #   run: |
        #     echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_REPO }} -u github-token --password-stdin

        - name: Build and push Docker image
          run: |
            docker build -t ${{ secrets.ACR_REPO }}/myimage:${{ github.sha }} .
            docker tag ${{ secrets.ACR_REPO }}/myimage:${{ github.sha }} ${{ secrets.ACR_REPO }}/myimage:latest
            docker push ${{ secrets.ACR_REPO }}/myimage:${{ github.sha }}
            docker push ${{ secrets.ACR_REPO }}/myimage:latest